---
- name: Test the server connection
  hosts: server
  tasks:
    - name: Ping the server
      ansible.builtin.ping:
      register: message
    - name: Print message
      ansible.builtin.debug:
        msg: '{{ message }}'

- name: Install pip
  hosts: server
  roles:
    - role: pip
      become: true
