---
- name: Test the server connection
  hosts: server
  tasks:
    - name: Ping the server
      ansible.builtin.ping:
      register: message
    - name: Print message
      ansible.builtin.debug:
        msg: '{{ message }}'

# - name: Install pip
#   hosts: server
#   roles:
#     - role: pip
#       become: true

- name: Install nvm & NodeJS
  hosts: server
  tasks:
    - name: Download nvm
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.2/install.sh
        dest: /tmp/install.sh
        mode: 0755
    - name: Install nvm
      ansible.builtin.command: /tmp/install.sh
      args:
        creates: '{{ ansible_env.HOME }}/.nvm/nvm.sh'

- name: Install Nginx
  hosts: server
  tasks:
    - name: Check if NGINX is installed
      ansible.builtin.package_facts:
        manager: 'auto'
    - name: Install Nginx
      ansible.builtin.package:
        name: nginx
        state: present
      become: true
      when: "'nginx' not in ansible_facts.packages"
    - name: Start Nginx
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true
      become: true
